### PR TITLE
Usage of Criptographic Primitive Analysis plugin

### PR DESCRIPTION
**Pull request by WalkinParadox**
-----Plugin for usage of cryptographic primitives in sourcecode.

The plugin takes as input the application objects, it invokes sonarqube to analyze all files in the directories specified in the config.yaml, after the analysis it checks if the smell in question appears in the result of the sonarqube analysis.

The plugin works perfectly for python, php, js, java, kotlin e typescript sourceocde.It needs to be extended for c# and vbnet analysis (by running msbuild on an extra container). These files at the moment get skipped by sonarqube.

The plugin runs a sonarqube server on a docker container and sonarscanner on a different docker container.

-----Example of UCP analysis functioning correctly

I created an example project (usage_of_cryptographic_primitives), it consists of:
-a config.yaml file, where the sourcecode paths will be specified.
-various sourcecode files written in diiferent languages (python, php, js, java, kotlin e typescript, and a vbnet file that will be skipped by the analysis tool) 
-a readme.md file

### CODE REVIEW

**Comment by jsoldani** [comment]
@gio54321 can you please give a first check to the PR? :-)

**Review by gio54321 — CHANGES_REQUESTED** [review]
Thanks for the PR and sorry for the delay. :sweat_smile: 

I took a look at the code and in general it seems very good to me. Unfortunately I was not able to run the test, first of all because the sonarqube client was not present in the `pyproject.toml`. I tried adding it to the project using `poetry add python-sonarqube-api` but I faced this error:

```
    sonar.auth.authenticate_user(login="admin", password="admin")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SonarQubeAuth' object has no attribute 'authenticate_user'
```
maybe the `python-sonarqube-api` package is not the correct one to use?

A couple of things on the analysis code:
- first I would split up the large body into some functions, to improve readability.
- Also I suggest adding a `try ... finally` block when creating the Docker container (something like [this](https://github.com/di-unipi-socc/kube-hound/blob/master/kube_hound/builtin_analyses/unnecessary_privileges_pods.py#L35-L53)) to handle the destruction and cleanup of the container, because if an exception is raised, the container remains running and has to be manually stopped from the docker cli.

**Comment by WalkinParadox** [comment]
I've resolved the issue , and cleaned up the code by applying the changes you suggested:

-Split up the code in multiple functions;
-Inserted the "try...finally" to clean up the code;
-Removed the code that was blocking the plugin from working;

One thing to highlight is that because the plugin has to wait for the sonarqube server to be running it takes a bit longer to execute compared to other plugins.

**Comment by jsoldani** [comment]
@WalkinParadox can you please check the to-be-resolved conflicts of your PR?

**Comment by jsoldani** [comment]
Thanks, @WalkinParadox. @gio54321 can you please check whether the requested changes are ok now?

**Comment by WalkinParadox** [comment]
Ho trovato un errore nel codice, non so per quale motivo ho confuso le chiavi da guardare nell'analisi di sonarqube, correggo il codice e riaggiorno i test. Al momento infatti non creano custom crypto ma usano crypto non custom debole. Magari nel frattempo chiudo la pull request?

**Comment by jsoldani** [comment]
Si, forse meglio chiuderla e riaprirla quando hai sistemato tutto. Così ricontrolliamo il codice rivisto e corretto :-)

**Pull request closed without merging**
