### PR TITLE
Suspicious Cryptographic Names Plugin

### PR DESCRIPTION
**Pull request by thowardg**
Added Suspicious Crypto Names detection to Kubehound.

The base_analysis function works on all types of files; it takes the file as input and splits the text into single words. Each word is analyzed for presence of suspicious keywords; every suspicious word is then searched for in the file in order to find its line.

Python, java and javascript files are dealt with differently:
For each one of these file types the plugin will utilize specific python libraries in order to build abstract syntax trees (AST),
For each tree the tool will look at the node type and node name in order to find suspicious names in the files.

This procedure is not yet easily implementable in python for other file types as building asts is not as easy.

The plugin at the current state ignores certain types of files that can be modified.
It can be changed to only be working on a select few languages if we prefer.

It also ignore a few words that would be considered suspicious but aren't, such as "private", "positive" and "negative";

In future one could add the possibility of asking the user for what files to ignore and words deemed by the user as not suspicious.

------------------------------

For the test i used the same mock application that i created for the UCP analysis with some updated files.

------------------------------
THINGS TO LOOK OUT FOR:
------------------------------

One thing to maybe look at is the way the plugin notifies the user of the smell; In it's current fork kubehound will show a notification for every suspicious word in every file; this leads to a long message on the terminal.

The other thing is if we prefer to choose the file types to analyze, or if we prefer to define the file types to skip during the analysis.

@gio54321 @jsoldani

### CODE REVIEW

**Comment by gio54321** [comment]
Hi @WalkinParadox, thanks for the PR! I tested and the new plugin works very well, finding all expected instances of `OCC` smell. I think the implementation for python and java files that actually parses the AST of the source code is an excellent feature of the plugin!

Before merging, I have a couple of minor suggestions:
- I think the `esprima` dependency is missing rom the poetry init and lock files,
- the output is indeed kind of long, maybe we could re-format the output, aggregating the smells coming from same file, something like
```
Suspicious Cryptographic Names - detected smells {OCC}
	Potential usage of custom crypto code in test_ucp.kt at lines: 4, 16:
	>   IvParameterSpec
	At lines: 8, 9, 18, 19, 22:
	>   AES
	At lines: 9, 10, 11:
	>   aesKeyGenerator
	At lines: 9, 10, 11, 23, 27:
	>   aesKey
	At lines: 13, 15, 16, 23, 27, 45:
	>   iv
	At lines: 14, 15:
	>   aesRandom
	[and so on...]
	reason: Suspicious name found in the file, may indicate implementation of custom crypto code.
	Check for custom code implementation.
```

or another more compact option, since we are printing relatively short symbols and not full lines of code
```
Suspicious Cryptographic Names - detected smells {OCC}
	Potential usage of custom crypto code in test_ucp.kt:
	- "IvParameterSpec" at lines: 4, 16
	- "AES" at lines: 8, 9, 18, 19, 22
	- "aesKeyGenerator" at lines: 9, 10, 11
	- "aesKey" at lines: 9, 10, 11, 23, 27
	- "iv" at lines: 13, 15, 16, 23, 27, 45
	- "aesRandom" at lines: 14, 15
	[and so on...]
	reason: Suspicious name found in the file, may indicate implementation of custom crypto code.
	Check for custom code implementation.
```

**Comment by WalkinParadox** [comment]
@gio54321 thanks for the review, I readded esprima to poetry and improved the result message to make it look like the second example you made.

Should be ready for the merge now.

**Review by gio54321 — APPROVED** [review]
LGTM, for me we can merge @jsoldani

**Comment by jsoldani** [comment]
Thank you, both! I'll merge, then

**Pull request merged**
