### PR TITLE
Sourcecode parsing added

### PR DESCRIPTION
**Pull request by WalkinParadox**
Sourcecode directory to be used for analysis can now be specified inside the config.yaml by using the key "sourcecode".
The value associated with the sourcecode key should be the relative path from the root of the service direcotory, can also have no value if the user wants to analyze the whol directory.

Test added to show that the path returns the local directory with all of its contents and is able to read the contents of each file.

NOTE: the test has an additional test to be excecuted only if the mock-app has been cloned loaclly beforehand, so for now has been commented out but has been tested and is working

### CODE REVIEW

**Review by gio54321 — COMMENTED** [review]
Looks great, thank you! I tested the changes and they work fine. I have looked at the code adn I have a few suggestions to improve it further.

I think that using an empty `sourcecode` field in the YAML config file is a bit confusing, we could replace it with
```yaml
sourcecode : ''
```
or even better in terms of clarity
```yaml
sourcecode: '.'
```
because using the empty field actually is equivalent to writing
```yaml
sourcecode: null
```
which in my opinion is not really clear to denote "the root directory relative to the repository".
FYI the Python library `pathlib` can handle paths at high level, and it lets you do things like
```py
>>> from pathlib import Path
>>> Path('/a/b/c') / Path('.')
PosixPath('/a/b/c')
```
to join paths in a "smart" way. The library is also used in other contexts by Kube-hound when dealing with paths.

Minor: the tests are great, but I think instead of printing some information, they should be kept minimal, just checking some properties about the results using `assert`. For example they could simply make sure that the source directory has been correctly read by the parser.

**Comment by WalkinParadox** [comment]
Thanks for the review, I'll make the changes.

**Comment by WalkinParadox** [comment]
Changed all the join paths with the recommended Path function. Used assert to check if the path that is parsed by the sourcecode_parser has been parced correctly. I left the option of seeing the directory strcture and the contents of the files when using -s when calling the test from terminal.

**Review by gio54321 — APPROVED** [review]
LGTM, waiting for @jsoldani and then we can merge :slightly_smiling_face:

**Comment by jsoldani** [comment]
LGTM as well. I will proceed with merging the PR.

**Pull request merged**
